### ISSUE TITLE
From a couple of weeks, the discord integration is not working

### ISSUE THREAD

**Issue by jbinventor** [aislandener/discord-deckboard#20]
Been using Discord extension from the beginning, but from a couple of weeks the integration with Discord does not work.
Previously, when you executed Deckboard, Discord opened a pop-up asking you to grant permissions to Deckboard. But now, this pop-up window does not appear, and the buttons do not work anymore.

**Comment by rivafarabi** [comment]
Can someone with this issue drop the link to the log file? 
The log file can be exported from the Deckboard configs.

**Comment by jbinventor** [comment]
Hi @rivafarabi  Have you made any change?? I use Deckboard usually, and this extension was not working from, not sure, but about 1 month or more. Now, you post this message asking for logs, I swich on my PC, and it worked!

**Comment by jbinventor** [comment]
Hi @rivafarabi 

I've been investigating, and I can reproduce the issue. I have Windows 10 Pro 22H2, with 2 user accounts (let's name them UserA and UserB). Here is how I can reproduce the issue:

1. Log in to Windows with UserA.
2. Restart Windows.
3. Log in to Windows with UserB.
4. Run Discord
5. Run Deckboard (**at this point, the Discord extension didn't work**)
6. But, then, if you restart Windows (with the logged-in UserB)
7. Log in to Windows with UserB.
8. Run Discord
9. Run Deckboard (**at this point, the Discord extension worked!**)

These are the log for each restart:

First restart (steps 1 to 5):
```
[2024-07-12 21:22:28.364] [info]  Connecting database in C:\Program Files\Deckboard\resources\database.db
[2024-07-12 21:22:28.369] [info]  Checking for update
[2024-07-12 21:22:28.599] [error] adb:startDeviceTracker Error: spawn adb ENOENT
    at ChildProcess._handle.onexit (node:internal/child_process:286:19)
    at onErrorNT (node:internal/child_process:484:16)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21)
[2024-07-12 21:22:30.003] [info]  Update for version 3.0.4 is not available (latest version: 3.0.4, downgrade is disallowed).
[2024-07-12 21:22:35.287] [error] obs:sendCurrentStatus Error: Not connected
    at OBSWebSocket.message (C:\Program Files\Deckboard\resources\app.asar\node_modules\obs-websocket-js\dist\json.cjs:652:15)
    at OBSWebSocket.call (C:\Program Files\Deckboard\resources\app.asar\node_modules\obs-websocket-js\dist\json.cjs:502:37)
    at t.<anonymous> (C:\Program Files\Deckboard\resources\app.asar\dist\main\index.js:2:129013)
    at h (C:\Program Files\Deckboard\resources\app.asar\dist\main\index.js:2:112250)
    at Generator.<anonymous> (C:\Program Files\Deckboard\resources\app.asar\dist\main\index.js:2:113592)
    at Generator.next (C:\Program Files\Deckboard\resources\app.asar\dist\main\index.js:2:112679)
    at u (C:\Program Files\Deckboard\resources\app.asar\dist\main\index.js:2:118728)
    at a (C:\Program Files\Deckboard\resources\app.asar\dist\main\index.js:2:118931)
    at C:\Program Files\Deckboard\resources\app.asar\dist\main\index.js:2:118990
    at new Promise (<anonymous>)
    at t.<anonymous> (C:\Program Files\Deckboard\resources\app.asar\dist\main\index.js:2:118871)
    at t.<anonymous> (C:\Program Files\Deckboard\resources\app.asar\dist\main\index.js:2:130020)
    at t.value (C:\Program Files\Deckboard\resources\app.asar\dist\main\index.js:2:90507)
    at Namespace.<anonymous> (C:\Program Files\Deckboard\resources\app.asar\dist\main\index.js:2:170288)
    at Namespace.emit (node:events:514:28)
    at Namespace.emit (C:\Program Files\Deckboard\resources\app.asar\node_modules\socket.io\lib\namespace.js:219:10)
[2024-07-12 21:22:46.538] [error] obs:sendCurrentStatus Error: Not connected
    at OBSWebSocket.message (C:\Program Files\Deckboard\resources\app.asar\node_modules\obs-websocket-js\dist\json.cjs:652:15)
    at OBSWebSocket.call (C:\Program Files\Deckboard\resources\app.asar\node_modules\obs-websocket-js\dist\json.cjs:502:37)
    at t.<anonymous> (C:\Program Files\Deckboard\resources\app.asar\dist\main\index.js:2:129013)
    at h (C:\Program Files\Deckboard\resources\app.asar\dist\main\index.js:2:112250)
    at Generator.<anonymous> (C:\Program Files\Deckboard\resources\app.asar\dist\main\index.js:2:113592)
    at Generator.next (C:\Program Files\Deckboard\resources\app.asar\dist\main\index.js:2:112679)
    at u (C:\Program Files\Deckboard\resources\app.asar\dist\main\index.js:2:118728)
    at a (C:\Program Files\Deckboard\resources\app.asar\dist\main\index.js:2:118931)
    at C:\Program Files\Deckboard\resources\app.asar\dist\main\index.js:2:118990
    at new Promise (<anonymous>)
    at t.<anonymous> (C:\Program Files\Deckboard\resources\app.asar\dist\main\index.js:2:118871)
    at t.<anonymous> (C:\Program Files\Deckboard\resources\app.asar\dist\main\index.js:2:130020)
    at t.value (C:\Program Files\Deckboard\resources\app.asar\dist\main\index.js:2:90507)
    at Namespace.<anonymous> (C:\Program Files\Deckboard\resources\app.asar\dist\main\index.js:2:170288)
    at Namespace.emit (node:events:514:28)
    at Namespace.emit (C:\Program Files\Deckboard\resources\app.asar\node_modules\socket.io\lib\namespace.js:219:10)
```

Second restart (steps 6 to 9):

```
[2024-07-12 21:27:01.097] [info]  Connecting database in C:\Program Files\Deckboard\resources\database.db
[2024-07-12 21:27:01.102] [info]  Checking for update
[2024-07-12 21:27:01.244] [error] adb:startDeviceTracker Error: spawn adb ENOENT
    at ChildProcess._handle.onexit (node:internal/child_process:286:19)
    at onErrorNT (node:internal/child_process:484:16)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21)
[2024-07-12 21:27:02.636] [info]  Update for version 3.0.4 is not available (latest version: 3.0.4, downgrade is disallowed).
[2024-07-12 21:27:13.861] [error] obs:sendCurrentStatus Error: Not connected
    at OBSWebSocket.message (C:\Program Files\Deckboard\resources\app.asar\node_modules\obs-websocket-js\dist\json.cjs:652:15)
    at OBSWebSocket.call (C:\Program Files\Deckboard\resources\app.asar\node_modules\obs-websocket-js\dist\json.cjs:502:37)
    at t.<anonymous> (C:\Program Files\Deckboard\resources\app.asar\dist\main\index.js:2:129013)
    at h (C:\Program Files\Deckboard\resources\app.asar\dist\main\index.js:2:112250)
    at Generator.<anonymous> (C:\Program Files\Deckboard\resources\app.asar\dist\main\index.js:2:113592)
    at Generator.next (C:\Program Files\Deckboard\resources\app.asar\dist\main\index.js:2:112679)
    at u (C:\Program Files\Deckboard\resources\app.asar\dist\main\index.js:2:118728)
    at a (C:\Program Files\Deckboard\resources\app.asar\dist\main\index.js:2:118931)
    at C:\Program Files\Deckboard\resources\app.asar\dist\main\index.js:2:118990
    at new Promise (<anonymous>)
    at t.<anonymous> (C:\Program Files\Deckboard\resources\app.asar\dist\main\index.js:2:118871)
    at t.<anonymous> (C:\Program Files\Deckboard\resources\app.asar\dist\main\index.js:2:130020)
    at t.value (C:\Program Files\Deckboard\resources\app.asar\dist\main\index.js:2:90507)
    at Namespace.<anonymous> (C:\Program Files\Deckboard\resources\app.asar\dist\main\index.js:2:170288)
    at Namespace.emit (node:events:514:28)
    at Namespace.emit (C:\Program Files\Deckboard\resources\app.asar\node_modules\socket.io\lib\namespace.js:219:10)
```

So, if anybody has this issue, try to restart Windows with the same user you use with Discord/Deckboard.

Hope this helps!

Kind regards.
