### ISSUE TITLE
What happens when you get this setup correctly

### ISSUE THREAD

**Issue by MaxxRK** [aislandener/discord-deckboard#4]

**Comment by MaxxRK** [comment]
Can you tell me where to get this access token at I have this thing working, but everytime I try to use an action it pops up the pop up in discord asking you to authorize.

**Comment by Yoween** [comment]
Hi, I hope you found a way to fix it. If not here's what I've done : 
1) Clear those fields and click "Save"
![image](https://user-images.githubusercontent.com/82267191/170460768-790f941a-f01f-40ef-8928-36b2af0e3992.png)
2) Restart Deckboard
3) Go to developper portal and make sure to fill correctly "Redirect"
4) Click on "Reset Secret"  WATCHOUT! You will have to change it everywhere it's used otherwise your other apps won't work
![image](https://user-images.githubusercontent.com/82267191/170461725-65f28d95-4a32-4f5b-a0f2-6ef68998edeb.png)
5) Copy your Client ID and your Client Secret (that you just reset) from the Dev Portal and go to Deckboard Extensions Configs to paste it there and click "save".
6) Open Discord, wait for it to start and open Deckboard
7) The Discord token window should open, click "Yes", copy the Token ID into Deckboard, save, and restart both (Dicord first then Deckboard). 

It works for me, so I hope I helped you!

**Comment by Curtis-Crouch** [comment]
I'm having the same issue.  Followed all instructions but I cannot get Discord to pop the Access Token screen ... I REALLY want to be able to use this app in Deckboard, but so far its proving impossible.

I think I saw somewhere the Developer saying they would make a video, but I've not seen any follow up on that.

Clearly I must be missing something (though I have no idea what!), do I need to enable something in Discord first?

**Comment by zeitos** [comment]
same here, in linux I get: 
``` [15:15:06.961] [error] Error: Could not connect
    at Socket.onerror (/tmp/deckboard-extensions/discord-deckboard.asar/node_modules/discord-rpc/src/transports/ipc.js:32:16)
    at Object.onceWrapper (events.js:273:13)
    at Socket.emit (events.js:182:13)
    at emitErrorNT (internal/streams/destroy.js:82:8)
    at emitErrorAndCloseNT (internal/streams/destroy.js:50:3)
    at process._tickCallback (internal/process/next_tick.js:63:19)
```
